use chrono::{Duration, Utc};
use settings::manager::SettingsManager;
use warpui::{App, SingletonEntity};

use crate::NetworkStatus;
use crate::ai::facts::{AIFact, AIMemory, CloudAIFact};
use crate::cloud_object::model::generic_string_model::GenericStringModel;
use crate::cloud_object::model::persistence::CloudModel;
use crate::cloud_object::{CloudObjectMetadata, CloudObjectPermissions, Owner, Revision};
use crate::notebooks::manager::NotebookManager;
use crate::search::ai_context_menu::rules::data_source::RulesDataSource;
use crate::search::data_source::Query;
use crate::search::mixer::SyncDataSource;
use crate::server::cloud_objects::update_manager::UpdateManager;
use crate::server::ids::SyncId;
use crate::server::server_api::ServerApiProvider;
use crate::settings::AISettings;
use crate::system::SystemStats;

fn mock_cloud_ai_fact(id: i64, name: &str, content: &str, revision: Revision) -> CloudAIFact {
    CloudAIFact::new(
        SyncId::from(id),
        GenericStringModel::new(AIFact::Memory(AIMemory {
            name: Some(name.to_string()),
            content: content.to_string(),
            is_autogenerated: false,
            suggested_logging_id: None,
        })),
        CloudObjectMetadata {
            folder_id: None,
            revision: Some(revision),
            metadata_last_updated_ts: None,
            current_editor_uid: None,
            trashed_ts: None,
            creator_uid: None,
            last_editor_uid: None,
        },
        CloudObjectPermissions {
            owner: Owner::mock_current_user(),
        },
    )
}

fn initialize_app(app: &mut App) {
    app.add_singleton_model(|_| NetworkStatus::new());
    app.add_singleton_model(|_| SystemStats::new());
    app.add_singleton_model(CloudModel::mock);
    app.add_singleton_model(|_ctx| UpdateManager::new(None));
    app.add_singleton_model(NotebookManager::mock);
    app.add_singleton_model(|_| ServerApiProvider::new_for_test());
    app.add_singleton_model(|_| SettingsManager::default());
    app.update(crate::settings::init_and_register_user_preferences);
    app.update(AISettings::register_and_subscribe_to_events);
}

#[test]
fn zero_state_scores_reflect_recency() {
    App::test((), |mut app| async move {
        initialize_app(&mut app);

        let now = Utc::now();
        CloudModel::handle(&app).update(&mut app, |model, _| {
            model.add_object(
                SyncId::from(1),
                mock_cloud_ai_fact(
                    1,
                    "oldest rule",
                    "oldest content",
                    (now - Duration::minutes(3)).into(),
                ),
            );
            model.add_object(
                SyncId::from(2),
                mock_cloud_ai_fact(
                    2,
                    "middle rule",
                    "middle content",
                    (now - Duration::minutes(2)).into(),
                ),
            );
            model.add_object(
                SyncId::from(3),
                mock_cloud_ai_fact(
                    3,
                    "newest rule",
                    "newest content",
                    (now - Duration::minutes(1)).into(),
                ),
            );
        });

        let data_source = RulesDataSource::new();
        let results = app.read(|app| data_source.run_query(&Query::from(""), app).unwrap());

        assert_eq!(results.len(), 3);
        let scores: Vec<_> = results.iter().map(|r| r.score()).collect();
        assert!(
            scores[0] > scores[1] && scores[1] > scores[2],
            "Expected scores in strictly descending order (newest first), got {scores:?}"
        );
    })
}

#[test]
fn filtered_state_adds_recency_bonus() {
    App::test((), |mut app| async move {
        initialize_app(&mut app);

        let now = Utc::now();
        // All rules contain "rule" so fuzzy scores should be similar
        CloudModel::handle(&app).update(&mut app, |model, _| {
            model.add_object(
                SyncId::from(1),
                mock_cloud_ai_fact(
                    1,
                    "my first rule",
                    "first rule content",
                    (now - Duration::minutes(3)).into(),
                ),
            );
            model.add_object(
                SyncId::from(2),
                mock_cloud_ai_fact(
                    2,
                    "my second rule",
                    "second rule content",
                    (now - Duration::minutes(2)).into(),
                ),
            );
            model.add_object(
                SyncId::from(3),
                mock_cloud_ai_fact(
                    3,
                    "my third rule",
                    "third rule content",
                    (now - Duration::minutes(1)).into(),
                ),
            );
        });

        let data_source = RulesDataSource::new();
        let results = app.read(|app| data_source.run_query(&Query::from("rule"), app).unwrap());

        assert_eq!(results.len(), 3);
        let scores: Vec<_> = results.iter().map(|r| r.score()).collect();
        assert!(
            scores[0] > scores[1] && scores[1] > scores[2],
            "Expected scores in strictly descending order (newest first), got {scores:?}"
        );
    })
}
