[package]
name = "warp_js"
authors = ["Warp Team <dev@warp.dev>"]
version = "0.1.0"
edition = "2024"
publish.workspace = true
license.workspace = true

[dependencies]
bincode.workspace = true
cfg-if.workspace = true
serde.workspace = true
thiserror.workspace = true
uuid.workspace = true
rquickjs.workspace = true

[features]
test-util = []
