[package]
authors = ["Warp Team <dev@warp.dev>"]
edition = "2024"
name = "warp_graphql"
version = "0.1.0"
publish.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
chrono.workspace = true
cynic.workspace = true
http_client.workspace = true
http.workspace = true
instant.workspace = true
log.workspace = true
reqwest.workspace = true
serde.workspace = true
thiserror.workspace = true
warp_core.workspace = true
warp_graphql_schema.workspace = true

[build-dependencies]
anyhow.workspace = true
cynic-codegen.workspace = true
